### ISSUE TITLE
Adding a channel resets the previous layout of a channel

### ISSUE THREAD

**Issue by arnauddieumegard** [eclipse/poosl#37] opened 2022-09-15 09:00 UTC
Lets assume the following model:
![image](https://user-images.githubusercontent.com/1576016/190361229-f995a679-2afe-4aff-99ab-2601492c43f5.png)

If I create a new channel between Production.Control and folder.in then the layout becomes:
![image](https://user-images.githubusercontent.com/1576016/190361551-27c24a64-cffe-421b-be3a-5b5a6f5261fc.png)

One may want the black square to stay at its previous location.

**Comment by wpiers** [comment] 2022-11-23 13:14
"in" and "Control" ports are both already connected to several ports, thus have a black square each (a ChannelCluster). When you connect those two, the two channel clusters are merged. If the channel is created started from "in", the "in" channel cluster is kept, the other is deleted and its edges are reconnected to the "in" cluster. And the other way around.

So basically the square does not move, it is merged with another. The relayout of the channels previously connected to the deleted ChannelCluster give a wrong impression of what happens. 

I will close this issue as the channel merging worked as intended but note that the layout of channel is already the subject of another issue, #29, so there are leads to improve the UX on this subject.

**Closed by wpiers** 2022-11-23 13:14 UTC
Labels: bug
